- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom # Corvax-JobSupervisors
  canBeAntag: false
  radioBold: true # A-13 upgraded chat system
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearToplaceBra # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesLace # Andromeda-Underwear
