[game]
hostname = "üõ∞Ô∏è Corvax ‚Äî –ê—Ç–∞—Ä–∞ üåå [TTS]"
desc = "[–¢—Ä–µ–±—É–µ—Ç—Å—è 20 —á–∞—Å–æ–≤ –Ω–∞ –¥—Ä—É–≥–æ–º —Å–µ—Ä–≤–µ—Ä–µ Corvax!]\n–ö–æ—Ä–≤–∞–∫—Å –ø–µ—Ä–≤—ã–π —Ä—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã–π –ø—Ä–æ–µ–∫—Ç –≤ Space Station 14.\n–ù–∞ —ç—Ç–æ–º —Å–µ—Ä–≤–µ—Ä–µ —Å—Ä–µ–¥–Ω–∏–µ —Ç—Ä–µ–±–æ–≤–∞–Ω–∏—è –∫ RP.\n[–ò–º–µ–µ—Ç—Å—è –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏—è TTS (Text-To-Speech)]"
map_pool = "CorvaxDefaultMapPool"
maxplayers = 150
soft_max_players = 70
map_rotation = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_hours = 20

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
