[game]
hostname = "üõ∞Ô∏è Corvax ‚Äî –ú–µ–π–Ω üöÄ [TTS]"
desc = "–ö–æ—Ä–≤–∞–∫—Å –ø–µ—Ä–≤—ã–π —Ä—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã–π –ø—Ä–æ–µ–∫—Ç –≤ Space Station 14.\n–ù–∞ –ú–µ–π–Ω–µ –ø–æ–Ω–∏–∂–µ–Ω–Ω—ã–µ —Ç—Ä–µ–±–æ–≤–∞–Ω–∏—è –∫ RP.\n–ò–º–µ–µ—Ç—Å—è –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏—è TTS (Text-To-Speech)."
map_pool = "CorvaxDefaultMapPool"
maxplayers = 190
soft_max_players = 105
map_rotation = true

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:low,rp:med,region:eu_e,tts"
