#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

#Space Ninja Outfit
- type: startingGear
  id: SpaceNinjaGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    # belt holds katana so satchel has the tools for sabotaging things
    back: ClothingBackpackSatchelTools
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: AgentIDCard
    ears: ClothingHeadsetGrey
    pocket1: SpiderCharge
    pocket2: PinpointerStation
    belt: EnergyKatana
    suitstorage: OxygenTankFilled
    underwearb: ClothingUnderwearBottomBoxersSpaceNinja # Andromeda-Underwear
  underweart: ClothingUnderwearTopSpaceNinja # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesSpaceNinja # Andromeda-Underwear
  inhand:
    - JetpackBlackFilled

#Deathsquad Outfit
- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquadFilled
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesVisionERT #A-13
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    suitstorage: AirTankFilled
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: EnergySword
    pocket2: EnergyShield
    belt: ClothingBeltMilitaryWebbingMedFilled
    underwearb: ClothingUnderwearBottomBoxersDeathSquad # Andromeda-Underwear
  underweart: ClothingUnderwearTopDeathBra # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesDeathSquad # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack

# Syndicate Operative Outfit - Monkey
- type: startingGear
  id: SyndicateOperativeGearMonkey
  equipment:
    head: ClothingHeadHatOutlawHat
    jumpsuit: ClothingUniformJumpsuitOperative
    mask: CigaretteSyndicate
  innerClothingSkirt: ClothingUniformJumpsuitOperative

# Syndicate Operative Outfit - Barratry
- type: startingGear
  id: SyndicateOperativeGearExtremelyBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Syndicate Operative Outfit - Basic
- type: startingGear
  id: SyndicateOperativeGearBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombatFilled
    pocket1: BaseUplinkRadio40TC
    id: SyndiPDA
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Syndicate Operative Outfit - Full Kit
- type: startingGear
  id: SyndicateOperativeGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    neck: SyndicateWhistle
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieCommander
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative
  inhand:
    - NukeOpsDeclarationOfWar

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperativeMedic
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieMedic
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiAgentPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbingMedFilled
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperativeMedic
  duffelbag: ClothingBackpackDuffelSyndicateOperativeMedic

#Syndicate Lone Operative Outfit - Full Kit
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio60TC
    belt: ClothingBeltMilitaryWebbing
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelSyndicateOperative

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled

#CBURN Unit Gear - Full Kit
- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURNFilled
    mask: ClothingMaskGasERT
    eyes: ClothingEyesVisionERT #A-13
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    suitstorage: OxygenTankFilled
    belt: ClothingBeltBandolier
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpsuitColorBrown
  satchel: ClothingBackpackDuffelCBURNFilled
  duffelbag: ClothingBackpackDuffelCBURNFilled

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    id: PunPunIDCard

# Passenger but without the ID, bag, or headset

- type: startingGear
  id: LimitedPassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
  innerClothingSkirt: ClothingUniformJumpskirtColorGrey

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
  innerClothingSkirt: ClothingUniformJumpskirtColorWhite
  inhand:
    - WeaponMeleeToolboxRobust

#Brigmedic

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled
    underwearb: ClothingUnderwearBottomBoxersWhite # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraWhite # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Andromeda-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelBrigmedicFilled
  duffelbag: ClothingBackpackDuffelBrigmedicFilled

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelHoldingAdmin
    id: AdminPDA

#Head Rev Gear
- type: startingGear
  id: HeadRevGear
  equipment:
    pocket2: Flash

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult

#Banana Clown
- type: startingGear
  id: BananaClown
  equipment:
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana
